name: Lint
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: false

      - uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: v1.52
          args: --timeout=10m
