name: Lint
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: false

      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.52
          args: --timeout=10m
