name: Lint
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: 1.21.x

      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.52
          args: --timeout=10m
